// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv-eC13DRJIA6otmOlAe6qMUIGOGQ507c',
    appId: '1:21059802599:web:9993e160da5209d7045942',
    messagingSenderId: '21059802599',
    projectId: 'fleet-management-poc',
    authDomain: 'fleet-management-poc.firebaseapp.com',
    databaseURL: 'https://fleet-management-poc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fleet-management-poc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-xlDUegjGSQSLj1CfP30l_zNDTWJACa4',
    appId: '1:21059802599:android:8a82f2be099d1eab045942',
    messagingSenderId: '21059802599',
    projectId: 'fleet-management-poc',
    databaseURL: 'https://fleet-management-poc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fleet-management-poc.firebasestorage.app',
  );

}